### ISSUE TITLE
`tcp_port_scan_scapy.py` does not parse results correctly

### ISSUE THREAD

**Issue by rgerardi** [josevnz/StopUsingTelnetToTestPorts#2]
Hello @josevnz ,

I think there's an issue with `tcp_port_scan_scapy.py` not parsing the scan results correctly. I am scanning a machine that has 3 closed ports but the script reports all ports open.

Results running the simple Pything TCP scanner script:

```
google.com:80: OK
amazon.com:80: OK
dragon:22: OK
dragon:9090: ERROR
dragon:8086: ERROR
dragon:21: ERROR
```

Results running the same input file with the Scapy script:

```
OK -> 172.217.165.14:80
OK -> 54.239.28.85:80
OK -> 192.168.88.242:22
OK -> 192.168.88.242:9090
OK -> 192.168.88.242:8086
OK -> 192.168.88.242:21
```

As you can see, it should report ports `9090`, `8086`, and `21` as closed.

**Comment by josevnz** [comment]
I can reproduce the error, I think the issue is how I'm interpreting the response packets. Will debug and fix.

**Comment by josevnz** [comment]
Fixed, the new version also offers a more detailed port analysis:

```shell
[josevnz@dmaf5 StopUsingTelnetToTestPorts]$ ./scripts/tcp_port_scan_scapy.py data/port_scan.csv 
OPEN -> google.com:80
OPEN -> amazon.com:80
OPEN -> raspberrypi:22
OPEN -> raspberrypi:9090
OPEN -> raspberrypi:8086
CLOSED -> raspberrypi:21
FILTERED -> dmaf5:22
FILTERED -> dmaf5:80
```
